index:
   path: /home
   controller: App\Controller\MainPageControler::index

project:
   path: /project
   controller: App\Controller\MainPageControler::project

contact:
   path: /contact
   controller: App\Controller\MainPageControler::contact
   
login:
   path: /login
   controller: App\Controller\MainPageControler::login
   
